const express = require("express");
const ee = require("@google/earthengine");
const cors = require("cors");
const fs = require("fs");
const nodemailer = require("nodemailer"); 
require("dotenv").config();               

// ===============================
// 1. INITIALIZE APP & MIDDLEWARE
// ===============================
const app = express();
app.use(cors());
app.use(express.json()); // CRITICAL: Must be placed AFTER const app = express();

const port = 5000;

// ===============================
// 2. EARTH ENGINE AUTH
// ===============================
const privateKey = require("./privatekey.json");

ee.data.authenticateViaPrivateKey(privateKey, () => {
  ee.initialize(null, null,
    () => { console.log("Earth Engine initialized successfully"); },
    (err) => { console.error("EE initialization error:", err); }
  );
});

// ===============================
// 3. CONTACT / INQUIRY EMAIL API
// ===============================
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  }
});

app.post("/api/inquiry", async (req, res) => {
  const { name, org, subject, message } = req.body;

  const mailOptions = {
    from: process.env.EMAIL_USER,
    to: process.env.EMAIL_USER, 
    subject: `🚨 URHMS Alert: New Inquiry from ${name} (${org})`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; padding: 20px; border: 1px solid #333; background-color: #0f172a; color: #f9fafb; border-radius: 8px;">
        <h2 style="color: #6b9dfc; border-bottom: 1px solid #333; padding-bottom: 10px;">URHMS Command Center Log</h2>
        <p><strong>Sender:</strong> ${name}</p>
        <p><strong>Organization:</strong> ${org}</p>
        <p><strong>Category:</strong> ${subject ? subject.toUpperCase() : 'N/A'}</p>
        <br/>
        <div style="background-color: #1e293b; padding: 15px; border-radius: 6px; border-left: 4px solid #6b9dfc;">
          <p style="margin: 0; color: #cbd5f5;">${message}</p>
        </div>
        <br/>
        <p style="font-size: 12px; color: #64748b;">Automated message generated by the Uttarakhand Road Health Monitoring System.</p>
      </div>
    `
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log(`Email successfully sent from ${name}`);
    res.status(200).json({ success: true, message: "Transmission complete." });
  } catch (error) {
    console.error("Nodemailer Error:", error);
    res.status(500).json({ success: false, error: "Failed to send email." });
  }
});

// ===============================
// 4. EXISTING HAZARD APIs
// ===============================

// --- SLOPE API ---
app.get("/slope", (req, res) => {
  const lat = parseFloat(req.query.lat);
  const lon = parseFloat(req.query.lon);
  const point = ee.Geometry.Point([lon, lat]);

  const dem = ee.Image("USGS/SRTMGL1_003");
  const slope = ee.Terrain.slope(dem);

  const result = slope.reduceRegion({
    reducer: ee.Reducer.mean(),
    geometry: point,
    scale: 30
  });

  result.evaluate((data, err) => {
    if (err) { res.status(500).json({ error: err }); return; }
    res.json({ slope: data.slope });
  });
});

// --- SNOW API ---
app.get("/snow", (req, res) => {
  const lat = parseFloat(req.query.lat);
  const lon = parseFloat(req.query.lon);

  const elevation = 2000 + Math.random() * 1500;
  const slope = Math.random() * 40;
  const aspect = Math.random() * 360;
  let risk = "LOW";

  if (elevation > 2500 && (aspect > 315 || aspect <= 45)) risk = "CRITICAL ICE RISK";
  else if (slope > 30) risk = "AVALANCHE RISK";
  else if (elevation > 2200) risk = "MODERATE SNOW RISK";

  res.json({
    name: "Highway near location",
    status: elevation > 2300 ? "Snow Covered" : "Clear",
    elevation: elevation.toFixed(0),
    slope: slope.toFixed(1),
    aspect: aspect.toFixed(0),
    risk: risk
  });
});

// --- FLOOD API ---
app.get("/flood", (req, res) => {
  const lat = parseFloat(req.query.lat);
  const lon = parseFloat(req.query.lon);
  const date = req.query.date;
  const point = ee.Geometry.Point([lon, lat]).buffer(60);

  const dem = ee.Image("USGS/SRTMGL1_003");
  const slope = ee.Terrain.slope(dem);
  const water = ee.Image("JRC/GSW1_4/GlobalSurfaceWater").select("occurrence");
  const rivers = water.gt(50);
  const riverDist = rivers.not().fastDistanceTransform(256).multiply(30).rename("riverDist");

  const s1 = ee.ImageCollection("COPERNICUS/S1_GRD")
    .filterBounds(point)
    .filter(ee.Filter.listContains("transmitterReceiverPolarisation", "VV"))
    .filter(ee.Filter.eq("instrumentMode", "IW"))
    .select("VV");

  const dateEE = ee.Date(date);
  const before = s1.filterDate(dateEE.advance(-45, "day"), dateEE.advance(-15, "day")).median();
  const after = s1.filterDate(dateEE.advance(-5, "day"), dateEE.advance(5, "day")).median();

  const beforeLin = ee.Image(10).pow(before.divide(10));
  const afterLin = ee.Image(10).pow(after.divide(10));
  const ratio = beforeLin.divide(afterLin);
  const flood = ratio.gt(1.5).rename("flood");

  const stack = ee.Image.cat([flood, slope.rename("slope"), riverDist]);

  const stats = stack.reduceRegion({
    reducer: ee.Reducer.mean(), geometry: point, scale: 30, maxPixels: 1e9
  });

  stats.evaluate((data, err) => {
    if (err) { res.status(500).json({ error: err }); return; }

    const floodFrac = data.flood || 0;
    const slopeVal = data.slope || 0;
    const distVal = data.riverDist || 0;

    let status = "Clear";
    if (floodFrac > 0 && floodFrac <= 0.05) status = "Water Present";
    else if (floodFrac > 0.05 && floodFrac <= 0.20) status = "Excess Water";
    else if (floodFrac > 0.20) status = "Flooded";

    let risk = "LOW";
    if (slopeVal < 10 && distVal < 150) risk = "CRITICAL";
    else if (slopeVal < 15 && distVal < 400) risk = "MODERATE";

    res.json({
      name: "Highway near location",
      status: status,
      floodFrac: (floodFrac * 100).toFixed(1),
      slope: slopeVal.toFixed(1),
      riverDist: distVal.toFixed(0),
      risk: risk
    });
  });
});

// --- LOCAL GEOJSON MAPS ---
app.get("/highwayRisk", (req, res) => {
  try {
    const data = fs.readFileSync("./data/highwayRisk.geojson");
    res.json(JSON.parse(data));
  } catch (e) {
    res.status(404).json({ error: "highwayRisk.geojson not found." });
  }
});

app.get("/snowRisk", (req, res) => {
  try {
    const data = fs.readFileSync("./data/snowRisk.geojson");
    res.json(JSON.parse(data));
  } catch (e) {
    res.status(404).json({ error: "snowRisk.geojson not found." });
  }
});

// --- POINT DANGER API ---
app.get("/danger", (req, res) => {
  const lat = parseFloat(req.query.lat);
  const lon = parseFloat(req.query.lon);
  const point = ee.Geometry.Point([lon, lat]).buffer(100);

  const dem = ee.Image("USGS/SRTMGL1_003");
  const slope = ee.Terrain.slope(dem);
  const rainfall = ee.ImageCollection("NASA/GPM_L3/IMERG_V06")
    .filterDate("2023-08-01", "2023-08-31")
    .select("precipitationCal")
    .mean();

  const stack = ee.Image.cat([slope.rename("slope"), rainfall.rename("rainfall")]);

  const stats = stack.reduceRegion({
    reducer: ee.Reducer.mean(), geometry: point, scale: 30, maxPixels: 1e9
  });

  stats.evaluate((data, err) => {
    if (err) { res.status(500).send(err); return; }

    const s = data.slope || 0;
    const r = data.rainfall || 0;

    let cliffRisk = 10;
    if (s > 45) cliffRisk = 90;
    else if (s > 35) cliffRisk = 70;
    else if (s > 25) cliffRisk = 50;
    else if (s > 15) cliffRisk = 30;

    let rainRisk = 10;
    if (r > 15) rainRisk = 80;
    else if (r > 10) rainRisk = 60;
    else if (r > 5) rainRisk = 40;

    const riskScore = Math.round(cliffRisk * 0.7 + rainRisk * 0.3);
    let status = "SAFE";
    if (riskScore > 70) status = "EXTREME DANGER";
    else if (riskScore > 50) status = "HIGH RISK";
    else if (riskScore > 30) status = "MODERATE RISK";

    res.json({
      slope: s.toFixed(1),
      rainfall: r.toFixed(2),
      cliffRisk,
      rainRisk,
      riskScore,
      status
    });
  });
});

// ===============================
// 5. START SERVER
// ===============================
app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});